/// Return all migrations as (version, name, sql).
///
/// The initial migration SQL is embedded from the migrations/ directory.
/// The schema_migrations table is created in Database::migrate() bootstrap,
/// so we skip re-creating it here and just run the rest of the schema.
pub fn get_migrations() -> Vec<(i64, &'static str, &'static str)> {
    vec![
        (
            1,
            "initial",
            include_str!("../../migrations/001_initial.sql"),
        ),
        (
            2,
            "config_to_db",
            include_str!("../../migrations/002_config_to_db.sql"),
        ),
        (
            3,
            "remove_protection",
            include_str!("../../migrations/003_remove_protection.sql"),
        ),
        (
            4,
            "app_blocking",
            include_str!("../../migrations/004_app_blocking.sql"),
        ),
        (
            5,
            "remote_sync_state",
            include_str!("../../migrations/005_remote_sync_state.sql"),
        ),
        (
            6,
            "hosts_blocking",
            include_str!("../../migrations/006_hosts_blocking.sql"),
        ),
        (
            7,
            "allowlist_schedule",
            include_str!("../../migrations/007_allowlist_schedule.sql"),
        ),
        (
            8,
            "missing_indexes",
            include_str!("../../migrations/008_missing_indexes.sql"),
        ),
        (
            9,
            "audit_and_sync_indexes",
            include_str!("../../migrations/009_audit_and_sync_indexes.sql"),
        ),
        (
            10,
            "audit_source",
            include_str!("../../migrations/010_audit_source.sql"),
        ),
    ]
}
